name: Build and Deploy

on:
  push:
    branches:
    - main

permissions:
  contents: read

env:
  LOGIN_SERVER: 'dannyongesaacr.azurecr.io'              # set this to login server for your private container registry (e.g. 'contoso.azurecr.io', 'index.docker.io' )
  REGISTRY: 'dannyongesaacr.azurecr.io'                 # set this to proper value for REGISTRY
  NAMESPACE: 'mbache'               # set this to proper value for NAMESPACE
  TAG: 'latest'                           # set this to proper value for TAG

jobs:
  BuildandDeploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build-Backend'
      shell: bash
      run: |
        # If your function app project is not located in your repository's root
        # Please change the path to your directory for docker build
        DOCKER_BUILDKIT=1 docker build -f backend.Dockerfile . -t ${{ env.REGISTRY }}/robopal/whatsapp-api:latest 
        docker push ${{ env.REGISTRY }}/robopal/whatsapp-api:latest

    - name: Azure logout
      run: |
        az logout
